// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVY0CSgt68G-QtZHZHmMW_wNeSm8SDGt4',
    appId: '1:294575534444:web:ad44f9a47632edbbd54349',
    messagingSenderId: '294575534444',
    projectId: 'moneyplanai',
    authDomain: 'moneyplanai.firebaseapp.com',
    storageBucket: 'moneyplanai.firebasestorage.app',
    measurementId: 'G-JCXM6XS22E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDV73MLVmytHBL-eo7m3peuniuBZm2Ru8o',
    appId: '1:294575534444:android:39769f5a5c6dad62d54349',
    messagingSenderId: '294575534444',
    projectId: 'moneyplanai',
    storageBucket: 'moneyplanai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMcMBoUkYtLReEswtv-Pkg6e9vlX0PlgY',
    appId: '1:294575534444:ios:68d9f90cd9271212d54349',
    messagingSenderId: '294575534444',
    projectId: 'moneyplanai',
    storageBucket: 'moneyplanai.firebasestorage.app',
    iosBundleId: 'com.example.moneyplanAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMcMBoUkYtLReEswtv-Pkg6e9vlX0PlgY',
    appId: '1:294575534444:ios:68d9f90cd9271212d54349',
    messagingSenderId: '294575534444',
    projectId: 'moneyplanai',
    storageBucket: 'moneyplanai.firebasestorage.app',
    iosBundleId: 'com.example.moneyplanAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVY0CSgt68G-QtZHZHmMW_wNeSm8SDGt4',
    appId: '1:294575534444:web:ce733dabddd27597d54349',
    messagingSenderId: '294575534444',
    projectId: 'moneyplanai',
    authDomain: 'moneyplanai.firebaseapp.com',
    storageBucket: 'moneyplanai.firebasestorage.app',
    measurementId: 'G-GYB5BJ96H6',
  );
}
